import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../css/home.module.css'
import ReactBsCarousel from '@/components/product/ReactBsCarousel'
import ProductList from './OriginProductList'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>PetPet佩佩星球</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  className={`${styles.main} ${inter.className}`} */}
      <main>
        <div className='container '>
        <ReactBsCarousel />
        <ProductList />
        </div>
      </main>
    </>
  )
}
